version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: IntegracionContinua
      MYSQL_USER: root
      MYSQL_PASSWORD: V@l3nt1n@1601
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d


